Fix Flask-Babel initialization for newer versions
- Changed from @babel.localeselector decorator to init_app() with locale_selector parameter
- Fixes AttributeError: 'Babel' object has no attribute 'localeselector'
- Compatible with Flask-Babel 4.0.0